<?php

return array(

    "p1"=>"As the first private capital risk investment institution and first angel investment institution of Henan province, Henan HuaXia Haina Venture Capital Group has been a leader brand in this area. Take the responsibility of promoting the development of China's venture capital business, stick to the core values of \"recognize now, invest in tomorrow,\" and adhere to the business philosophy of \"working, sharing and developing together\". We had developed and invested a group of leading science and technology projects and seed companies; we focusing on foster Henan future productivity and having been a pioneer and leader in Henan venture capital field.. ",
    "p2s"=>"Henan Huaxia Haina Sales and Marketing Co., Ltd.",
    "p2"=>"which is belong to Henan Huaxia Haina Investment Group gathers studying, designing, production and international marketing together as a marketing company.",
    "p3"=>"Relying on technology and service to reach development and continually provide clients satisfied products are our constant pursuit. Based on the full introduction of foreign advanced technology, we have successfully developed a variety of equipments which are widely used in advertising, architecture, medical, environmental protection and energy field etc. Huaxia Haina adhering to the “Quality of survival. Variety to development.” approach. And we continuously improve products quality and varieties to meet the market demand.",
    "p4s"=>"Now our company’s main business covers the following aspects:",
    "p5"=>"Advertising equipment (CNC routers, printers, banner machines, etc); paint; medical equipment (DNA extraction kit, uterine surgery ultrasound monitor). At the same time, our company also expands our business to the fields of environmental protection and energy sources.",
    "p6"=>"Our company pursues the guideline of “progress, practicability, preciseness , unity”, attaches great importance to technology and quality, and made continuous progress, dedicated to provide the customers the most cost effective products with attentive services.",
    "p7"=>"With expanding constantly, we increase the capital in operation. We purchased 32 acres of land to build a modern manufacturing plant with 20,000 square meters, which is supposed to be put on production in the middle of 2014. We attract customers from all directions by emphasizing basic function of integrity, superior quality products, reasonable price and favorable service. All staffs will stride forward to the higher goal, by enhancing the competitive strength in corn of themselves, holding on the spirit of forging ahead without any satisfaction.",
);